# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Thomas Gärtner
email: me@thomasgaertner.org
description: >- # this means to ignore newlines until "baseurl:"
  This will be the new version of my homepage at some point
baseurl: "/"
url: "http://127.0.0.1:4000/"
#url: "https://t-gaertner.github.io/"
twitter_username: none
github_username:  t-gaertner

# Build settings
markdown: kramdown
theme: minima
plugins: ['jekyll/scholar']
#  - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
permalink: /blog/:year/:month/:day/:title


scholar:
  style: apa
  locale: en

  sort_by: year
  order: descending

  group_by: none
  group_order: ascending

  source: ./_bibliography
  bibliography: someofmine.bib
  bibliography_template: ""

  replace_strings: true
  join_strings:    true

  use_raw_bibtex_entry: true

  details_dir:    bibliography
  details_layout: bibtex.html
  details_link:   Details

  query: "@*"
